<script lang="ts">
  import type { Component } from 'svelte';
  import {
    PanelLeftClose,
    PanelLeftOpen,
    Plus,
    Link,
    Folder,
    FolderTree,
    SquareTerminal,
    Search,
    ArrowLeft,
    RefreshCw,
    Menu,
    Bug,
    Share,
    SlidersHorizontal,
    Smartphone,
    Bell,
    Volume2,
    Camera,
    Image,
    ArrowUp,
    X,
    Minus,
    ChevronRight,
    ChevronDown,
    Copy,
    Square,
    Check,
    CircleDot,
    Circle,
    Loader,
    CircleArrowUp,
    ShieldOff,
    Info,
    Ellipsis,
    EllipsisVertical,
    // Additional icons for common UI patterns
    CircleStop,
    CircleX,
    CircleCheck,
    CircleAlert,
    TriangleAlert,
    Send,
    SendHorizontal,
    Trash,
    Trash2,
    Pencil,
    PencilLine,
    Settings,
    Settings2,
    Eye,
    EyeOff,
    File,
    FileText,
    FileCode,
    Download,
    Upload,
    ExternalLink,
    Clock,
    MessageSquare,
    ChevronUp,
    ChevronLeft,
    ArrowRight,
    ArrowDown,
    Maximize,
    Minimize,
    Save,
    Clipboard,
    Terminal,
    Code,
    Undo,
    Redo,
    LogOut,
    LogIn,
    User,
    Wifi,
    WifiOff,
    Zap,
    OctagonAlert,
    LoaderCircle,
    GitFork,
    Palette,
    Sparkles,
    Star,
  } from '@lucide/svelte';

  // Map of kebab-case icon name to Svelte component.
  // Keys match the names used in data-lucide="..." attributes in the vanilla HTML.
  const icons: Record<string, Component> = {
    // Icons actively used in the existing vanilla HTML
    'panel-left-close': PanelLeftClose,
    'panel-left-open': PanelLeftOpen,
    'plus': Plus,
    'link': Link,
    'folder': Folder,
    'folder-tree': FolderTree,
    'square-terminal': SquareTerminal,
    'search': Search,
    'arrow-left': ArrowLeft,
    'refresh-cw': RefreshCw,
    'menu': Menu,
    'bug': Bug,
    'share': Share,
    'sliders-horizontal': SlidersHorizontal,
    'smartphone': Smartphone,
    'bell': Bell,
    'volume-2': Volume2,
    'camera': Camera,
    'image': Image,
    'arrow-up': ArrowUp,
    'x': X,
    'minus': Minus,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'copy': Copy,
    'square': Square,
    'check': Check,
    'circle-dot': CircleDot,
    'circle': Circle,
    'loader': Loader,
    'circle-arrow-up': CircleArrowUp,
    'shield-off': ShieldOff,
    'info': Info,
    'ellipsis': Ellipsis,
    'ellipsis-vertical': EllipsisVertical,

    // Legacy aliases (for compatibility with older icon name references)
    'arrow-up-circle': CircleArrowUp,
    'stop-circle': CircleStop,
    'loader-2': Loader,
    'more-vertical': EllipsisVertical,
    'alert-octagon': OctagonAlert,
    'loader-circle': LoaderCircle,

    // Additional icons for common UI patterns
    'circle-stop': CircleStop,
    'circle-x': CircleX,
    'circle-check': CircleCheck,
    'circle-alert': CircleAlert,
    'triangle-alert': TriangleAlert,
    'send': Send,
    'send-horizontal': SendHorizontal,
    'trash': Trash,
    'trash-2': Trash2,
    'pencil': Pencil,
    'pencil-line': PencilLine,
    'settings': Settings,
    'settings-2': Settings2,
    'eye': Eye,
    'eye-off': EyeOff,
    'file': File,
    'file-text': FileText,
    'file-code': FileCode,
    'download': Download,
    'upload': Upload,
    'external-link': ExternalLink,
    'clock': Clock,
    'message-square': MessageSquare,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'arrow-right': ArrowRight,
    'arrow-down': ArrowDown,
    'maximize': Maximize,
    'minimize': Minimize,
    'save': Save,
    'clipboard': Clipboard,
    'terminal': Terminal,
    'code': Code,
    'undo': Undo,
    'redo': Redo,
    'log-out': LogOut,
    'log-in': LogIn,
    'user': User,
    'wifi': Wifi,
    'wifi-off': WifiOff,
    'zap': Zap,
    'octagon-alert': OctagonAlert,
    'git-fork': GitFork,
    'palette': Palette,
    'sparkles': Sparkles,
    'star': Star,
  };

  let {
    name,
    class: className = '',
    size = 16,
  }: {
    name: string;
    class?: string;
    size?: number;
  } = $props();

  const IconComponent = $derived(icons[name]);
</script>

{#if IconComponent}
  <IconComponent {size} class="lucide {className}" />
{/if}
