import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { RpcTest } from "@effect/rpc";
import { describe, it } from "@effect/vitest";
import { Effect, Layer, Queue, Stream } from "effect";
import { expect } from "vitest";
import { CLAUDE_TRUST_TIERED_SETTINGS_KEYS } from "../../../src/lib/contracts/claude-settings.js";
import {
	type ProjectSettingsEnvelope,
	WsRpcGroup,
} from "../../../src/lib/contracts/ws-rpc.js";
import { loadRelaySettings } from "../../../src/lib/relay/relay-settings.js";
import { WsRpcServerLayer } from "../../../src/lib/server/ws-rpc.js";
import {
	makeMockConfig,
	makeMockWebSocketHandler,
	makeTestHandlerLayer,
} from "../../helpers/mock-factories.js";

describe("WsRpcServerLayer Claude settings", () => {
	it.effect("reads, persists, and publishes global overrides", () => {
		const configDir = mkdtempSync(join(tmpdir(), "conduit-rpc-claude-"));

		return Effect.gen(function* () {
			const client = yield* RpcTest.makeClient(WsRpcGroup);
			const settings = yield* Queue.unbounded<ProjectSettingsEnvelope>();
			yield* Stream.runForEach(
				client.SubscribeProjectSettings({ projectSlug: "project-a" }),
				(envelope) => Queue.offer(settings, envelope),
			).pipe(Effect.forkScoped);
			yield* Queue.take(settings); // snapshot
			yield* Queue.take(settings); // synchronized
			expect(
				yield* client.GetClaudeSettings({ projectSlug: "project-a" }),
			).toEqual({
				projectSlug: "project-a",
				overrides: {},
			});

			const result = yield* client.SetClaudeSettings({
				projectSlug: "project-a",
				overrides: {
					autoCompactEnabled: false,
					attribution: { commit: "Generated by Conduit" },
				},
				originId: "browser-1",
			});

			expect(result.overrides).toEqual({
				autoCompactEnabled: false,
				attribution: { commit: "Generated by Conduit" },
			});
			expect(loadRelaySettings(configDir).claudeSettings).toEqual(
				result.overrides,
			);
			expect(yield* Queue.take(settings)).toMatchObject({
				_tag: "upsert",
				item: { _tag: "claudeSettings", overrides: result.overrides },
			});

			rmSync(configDir, { recursive: true, force: true });
		}).pipe(
			Effect.scoped,
			Effect.provide(
				WsRpcServerLayer.pipe(
					Layer.provideMerge(
						makeTestHandlerLayer({ config: makeMockConfig({ configDir }) }),
					),
				),
			),
		);
	});

	for (const key of CLAUDE_TRUST_TIERED_SETTINGS_KEYS) {
		it.effect(`rejects trust-tiered override ${key}`, () => {
			const configDir = mkdtempSync(join(tmpdir(), "conduit-rpc-claude-"));
			const wsHandler = makeMockWebSocketHandler();

			return Effect.gen(function* () {
				const client = yield* RpcTest.makeClient(WsRpcGroup);
				const result = yield* Effect.either(
					client.SetClaudeSettings({
						projectSlug: "project-a",
						overrides: { [key]: true },
					}),
				);

				expect(result._tag).toBe("Left");
				if (result._tag === "Left") {
					expect(result.left._tag).toBe("ClaudeSettingsTrustBoundaryError");
					if (result.left._tag === "ClaudeSettingsTrustBoundaryError") {
						expect(result.left.key).toBe(key);
						expect(result.left.message).toContain(key);
					}
				}
				expect(loadRelaySettings(configDir).claudeSettings).toBeUndefined();
				expect(wsHandler.broadcast).not.toHaveBeenCalled();
				rmSync(configDir, { recursive: true, force: true });
			}).pipe(
				Effect.scoped,
				Effect.provide(
					WsRpcServerLayer.pipe(
						Layer.provideMerge(
							makeTestHandlerLayer({
								config: makeMockConfig({ configDir }),
								wsHandler,
							}),
						),
					),
				),
			);
		});
	}
});
