// ─── Integration: Model Selection ────────────────────────────────────────────
// Tests model/provider behavior against a mock OpenCode server.
// Verifies:
//   - Only configured providers appear in model_list
//   - Model switch works and messages succeed
//   - New session resets model selection

import {
	afterAll,
	assert,
	beforeAll,
	beforeEach,
	describe,
	expect,
	it,
} from "vitest";
import {
	createRelayHarness,
	type RelayHarness,
} from "../helpers/relay-harness.js";

describe("Integration: Model Selection", () => {
	let harness: RelayHarness;

	beforeAll(async () => {
		harness = await createRelayHarness();
	}, 30_000);

	afterAll(async () => {
		if (harness) await harness.stop();
	});

	beforeEach(() => {
		harness.mock.resetQueues();
	});

	it("model_list only contains configured providers", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		await client.waitFor("model_list");
		const modelList = client.getReceivedOfType("model_list");
		expect(modelList.length).toBeGreaterThan(0);
		const modelListMessage = modelList[0];
		assert.exists(modelListMessage, "expected a model list message");
		const providers = modelListMessage["providers"] as Array<{
			id: string;
			name: string;
			configured: boolean;
			models: Array<{ id: string }>;
		}>;

		// Every provider in the list must be configured
		for (const provider of providers) {
			expect(provider.configured).toBe(true);
		}

		// Must have at least one provider with models
		const withModels = providers.filter((p) => p.models.length > 0);
		expect(withModels.length).toBeGreaterThan(0);

		await client.close();
	}, 15_000);

	it("receives model_info on connect", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Should have received model_info (auto-selected or from session)
		await client.waitFor("model_info");
		const modelInfos = client.getReceivedOfType("model_info");
		expect(modelInfos.length).toBeGreaterThan(0);
		const info = modelInfos[0];
		assert.exists(info, "expected a model info message");
		expect(typeof info["model"]).toBe("string");
		expect((info["model"] as string).length).toBeGreaterThan(0);

		await client.close();
	}, 15_000);

	it("SwitchModel RPC updates model_info broadcast", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Get available models from model_list
		await client.waitFor("model_list");
		const modelList = client.getReceivedOfType("model_list");
		const modelListMessage = modelList[0];
		assert.exists(modelListMessage, "expected a model list message");
		const providers = modelListMessage["providers"] as Array<{
			id: string;
			models: Array<{ id: string }>;
		}>;

		// Find a provider with at least one model
		const provider = providers.find((p) => p.models.length > 0);
		expect(provider).toBeDefined();
		assert.exists(provider, "expected a provider with models");
		const target = provider.models[0];
		assert.exists(target, "expected the provider to have a model");
		const targetModel = target.id;
		const targetProvider = provider.id;

		client.clearReceived();

		await client.switchModel(targetModel, targetProvider);

		// Should receive model_info broadcast
		const modelInfo = await client.waitFor("model_info");
		expect(modelInfo["model"]).toBe(targetModel);
		expect(modelInfo["provider"]).toBe(targetProvider);

		await client.close();
	}, 15_000);

	it("message succeeds after model switch", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Pick first model from first provider
		await client.waitFor("model_list");
		const modelList = client.getReceivedOfType("model_list");
		const modelListMessage = modelList[0];
		assert.exists(modelListMessage, "expected a model list message");
		const providers = modelListMessage["providers"] as Array<{
			id: string;
			models: Array<{ id: string }>;
		}>;
		const provider = providers.find((p) => p.models.length > 0);
		expect(provider).toBeDefined();
		assert.exists(provider, "expected a provider with models");
		const target = provider.models[0];
		assert.exists(target, "expected the provider to have a model");
		await client.switchModel(target.id, provider.id);

		await client.waitFor("model_info");
		client.clearReceived();

		// Send a message — should work with the selected model
		await client.sendMessage("Reply with just 'ok'.");

		// A fast replay can finish between status polls. Delta and done prove
		// the selected model's turn reached the client and completed.
		// The done event is generated by the status poller which consumes
		// GET /session/status queue entries independently — allow enough
		// time for it to reach the busy→idle transition.
		await client.waitFor("delta");
		const done = await client.waitFor("done", { timeout: 15_000 });
		expect(done["code"]).toBe(0);

		await client.close();
	}, 30_000);

	it("CreateSession RPC resets model selection without breaking messages", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Switch model explicitly — pick first from model list
		await client.waitFor("model_list");
		const modelList = client.getReceivedOfType("model_list");
		const modelListMessage = modelList[0];
		assert.exists(modelListMessage, "expected a model list message");
		const providers = modelListMessage["providers"] as Array<{
			id: string;
			models: Array<{ id: string }>;
		}>;
		const provider = providers.find((p) => p.models.length > 0);
		expect(provider).toBeDefined();
		assert.exists(provider, "expected a provider with models");
		const target = provider.models[0];
		assert.exists(target, "expected the provider to have a model");
		await client.switchModel(target.id, provider.id);

		await client.waitFor("model_info");

		// Create a new session — should reset model selection
		client.clearReceived();
		await client.createSession("Model Reset Test");
		const switched = await client.waitFor("session_switched");

		await client.waitFor("session_family", {
			predicate: (message) =>
				Array.isArray(message["sessions"]) &&
				message["sessions"].some(
					(session: { id: string }) => session.id === switched["id"],
				),
		});
		client.clearReceived();

		// Send a message in the new session — should work
		await client.sendMessage("Reply with just 'ok'.");

		// The key assertion: the new session accepts messages (enters processing).
		const status = await client.waitFor("status", {
			predicate: (m) => m["status"] === "processing",
		});
		expect(status["status"]).toBe("processing");

		// Wait for either done (fast) or result (model is working, just slow to finalize)
		const evidence = await Promise.race([
			client.waitFor("done"),
			client.waitFor("result"),
		]);
		expect(evidence.type).toMatch(/^(done|result)$/);

		await client.close();
	}, 120_000);
});
