// Tests model/provider behavior against a mock OpenCode server.
// Verifies:
//   - Only configured providers appear in GetModels
//   - Model switch works and messages succeed
//   - New session resets model selection

import {
	afterAll,
	assert,
	beforeAll,
	beforeEach,
	describe,
	expect,
	it,
} from "vitest";
import {
	createRelayHarness,
	type RelayHarness,
} from "../helpers/relay-harness.js";

describe("Integration: Model Selection", () => {
	let harness: RelayHarness;

	beforeAll(async () => {
		harness = await createRelayHarness();
	}, 30_000);

	afterAll(async () => {
		if (harness) await harness.stop();
	});

	beforeEach(() => {
		harness.mock.resetQueues();
	});

	it("GetModels only returns configured providers", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		const { providers } = await client.getModels();

		// Every provider in the list must be configured
		for (const provider of providers) {
			expect(provider.configured).toBe(true);
		}

		// Must have at least one provider with models
		const withModels = providers.filter((p) => p.models.length > 0);
		expect(withModels.length).toBeGreaterThan(0);

		await client.close();
	}, 15_000);

	it("GetModels reports an active model on connect", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Auto-selected or from the session.
		const { active } = await client.getModels();
		assert.exists(active, "expected an active model");
		expect(active.model.length).toBeGreaterThan(0);

		await client.close();
	}, 15_000);

	it("SwitchModel RPC records the session's model", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Get available models from GetModels
		const { providers } = await client.getModels();

		// Find a provider with at least one model
		const provider = providers.find(
			(p) => p.id !== "claude" && p.models.length > 0,
		);
		expect(provider).toBeDefined();
		assert.exists(provider, "expected a provider with models");
		const target = provider.models[0];
		assert.exists(target, "expected the provider to have a model");
		const targetModel = target.id;
		const targetProvider = provider.id;

		await client.switchModel(targetModel, targetProvider);

		const { active } = await client.getModels();
		expect(active).toEqual({ model: targetModel, provider: targetProvider });

		await client.close();
	}, 15_000);

	it("message succeeds after model switch", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Pick first model from first provider
		const { providers } = await client.getModels();
		const provider = providers.find(
			(p) => p.id !== "claude" && p.models.length > 0,
		);
		expect(provider).toBeDefined();
		assert.exists(provider, "expected a provider with models");
		const target = provider.models[0];
		assert.exists(target, "expected the provider to have a model");
		await client.switchModel(target.id, provider.id);
		client.clearReceived();

		// Send a message — should work with the selected model
		await client.sendMessage("Reply with just 'ok'.");

		// A fast replay can finish between status polls. Delta and done prove
		// the selected model's turn reached the client and completed.
		// The done event is generated by the status poller which consumes
		// GET /session/status queue entries independently — allow enough
		// time for it to reach the busy→idle transition.
		await client.waitFor("delta");
		const done = await client.waitFor("done", { timeout: 15_000 });
		expect(done["code"]).toBe(0);

		await client.close();
	}, 30_000);

	it("CreateSession RPC resets model selection without breaking messages", async () => {
		const client = await harness.connectWsClient();
		await client.waitForInitialState();

		// Switch model explicitly — pick first from model list
		const { providers } = await client.getModels();
		const provider = providers.find(
			(p) => p.id !== "claude" && p.models.length > 0,
		);
		expect(provider).toBeDefined();
		assert.exists(provider, "expected a provider with models");
		const target = provider.models[0];
		assert.exists(target, "expected the provider to have a model");
		await client.switchModel(target.id, provider.id);

		// Create a new session — should reset model selection
		client.clearReceived();
		await client.createSession("Model Reset Test");
		const switched = await client.waitFor("session_switched");

		await client.waitFor("session_family", {
			predicate: (message) =>
				Array.isArray(message["sessions"]) &&
				message["sessions"].some(
					(session: { id: string }) => session.id === switched["id"],
				),
		});
		client.clearReceived();

		// Send a message in the new session — should work
		await client.sendMessage("Reply with just 'ok'.");

		// The key assertion: the new session accepts messages (enters processing).
		const status = await client.waitFor("status", {
			predicate: (m) => m["status"] === "processing",
		});
		expect(status["status"]).toBe("processing");

		// Wait for either done (fast) or result (model is working, just slow to finalize)
		const evidence = await Promise.race([
			client.waitFor("done"),
			client.waitFor("result"),
		]);
		expect(evidence.type).toMatch(/^(done|result)$/);

		await client.close();
	}, 120_000);
});
